### ISSUE TITLE
Not a health token

### ISSUE THREAD

**Issue by dytec** [tbensky/npct#2]
Got this project up and running but serial log says:

Device found: #C19:xxxxxxxxxxxxxxxxxxx
Not a health token

What could be causing this message?
Thanks for pointing in the right direction!

**Comment by tbensky** [comment]
Hello...this error pops up when the bluetooth name starting with #C19:
isn't formatted properly to have originated from another token.
Do you have the full #C19:... code I could look at?  I'll look into it and
get back to you ASAP.

Thanks, Tom
(You can contact me at tbensky@gmail.com.)

**Comment by tbensky** [comment]
Hello again--our last code merge had some problems related to the error you
saw "Device found: #C19:xxxxxxxxxxxxxxxxxxx
Not a health token." It has been fixed now.

Could you please:
1) reflash your esp32 using the newer version of npct.bin here:
https://github.com/tbensky/npct/blob/master/npct/build/npct.bin
2) redownload the chrome/config app here:
https://github.com/tbensky/npct/blob/master/configapp/config.html

Sorry about this.  I'd love to hear of any thoughts you have on this
project.

Thanks,
Tom

**Comment by tbensky** [comment]
fixed and rechecked with 10 min timeout on repeated encounters
